### ISSUE TITLE
Support DIGITALOCEAN_TOKEN environment variable

### ISSUE THREAD

**Issue by gongled** [essentialkaos/terrafarm#13]
Would be great to use `DIGITALOCEAN_TOKEN` environment to launch VMs using terrafarm. What do you think about this feature? How difficult to implement it? Thanks!

**Comment by andyone** [comment]
Easy. I will implement this feature in next realease.

**Comment by andyone** [comment]
Feature added in `0.6.0` (#14)

**Comment by gongled** [comment]
Thanks!
